apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: eu.gcr.io/kyma-project/external/istio
  tag: 1.8.2-distroless
  components:
    egressGateways:
    - enabled: false
      name: istio-egressgateway
