apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        service:
          type: NodePort
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.ports
            value:
            - name: status-port
              port: 15021
              targetPort: 15021
              nodePort: 30002
            - name: http2
              port: 80
              targetPort: 80
              nodePort: 30000
            - name: https
              port: 443
              targetPort: 443
              nodePort: 30001
      name: istio-ingressgateway
