name: Tests on k3s (nodejs installer)

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'kyma-project/kyma'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
      skip:
        description: 'Skip modules'
        required: false
        default: 'monitoring,tracing,kiali,logging,console,cluster-users,dex'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Prepare docker registry and k3s
      run: |
        ./create-cluster-k3s.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    - name: Install Istio
      run: |
        ./install-istio.sh -f config-istio.yaml
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Install Kyma and run tests
      run: |
        ./download-kyma-charts.sh aerfio/kyma installler-in-action
        cd tests/fast-integration
        npm install
        DEBUG=true npm test
