name: Tests on k3s

on: 
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Prepare k3s and helm 3
      run: |
        mkdir -p ~/.kube
        if [[ -f ./kubeconfig ]];
        then
          echo "use existing kubeconfig"
          cp ./kubeconfig ~/.kube/config
        else
          echo "starting cluster"
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 INSTALL_K3S_EXEC="server --disable traefik" sh -
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          chmod 600 ~/.kube/config
        fi
        echo "Installing helm"
        curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    - name: Install Kyma
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
      run: |
        ./download-kyma-charts.sh
        ./install-kyma.sh
        sudo cp kyma.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Install Commerce Mock
      run: |
        ./commerce-mock.sh
    - name: Run End To End Test
      run: |
        ./app-connector-example.sh
