name: Tests on kind

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'kyma-project/kyma'
      branch:
        description: 'Branch'
        required: true
        default: 'main'
      skip:
        description: 'Skip modules'
        required: false
        default: 'monitoring,tracing,kiali,logging,console,cluster-users,dex'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Prepare docker registry, kind & helm 3
      run: |
        echo "Installing kind"
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.9.0
        echo "Starting docker registry & kind cluster"
        ./create-cluster-kind.sh
    - name: Install Kyma and Run Test
      env: 
        SKIP_MODULES: monitoring,tracing,kiali,logging,dex,console,helm-broker
      run: |
        SKIP=${{ github.event.inputs.skip }}
        export SKIP_MODULES=${SKIP:-$SKIP_MODULES}
        ./download-kyma-charts.sh ${{ github.event.inputs.repository }} ${{ github.event.inputs.branch }}
        cd tests/fast-integration
        npm install
        export DEBUG=true
        ./kyma.js install --new-eventing --skip-components $SKIP_MODULES
        npm run-script test-commerce-mock
