name: Tests on kind

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'kyma-project/kyma'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
      skip:
        description: 'Skip modules'
        required: false
        default: 'monitoring,tracing,kiali,logging,helm-broker,console,cluster-users,dex'
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Prepare docker registry, kind & helm 3
      run: |
        echo "Installing kind"
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.9.0
        echo "Starting docker registry & kind cluster"
        ./create-cluster-kind.sh
    - name: Install Istio
      run: |
        ./install-istio.sh -f config-istio-nodeport.yaml
    - name: Install Kyma
      env: 
        SKIP_MODULES: monitoring,tracing,kiali,logging,helm-broker,console,cluster-users,dex
      run: |
        SKIP=${{ github.event.inputs.skip }}
        export SKIP_MODULES=${SKIP:-$SKIP_MODULES}
        ./download-kyma-charts.sh ${{ github.event.inputs.repository }} ${{ github.event.inputs.branch }}
        ./install-kyma.sh
        sudo cp kyma.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Run End To End Test
      run: |
        ./app-connector-example.sh
